[package]
name = "rust-api-gateway"
version = "0.1.0"
edition = "2021"

# Dependencies
[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
